platform :ios, "9.0"

target "yydemo" do

pod 'FlutterApi', :path =>'../yyfluttermodule'

end

post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    configuration.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
  end
end
