platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Runner' do
  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, 'ios', 'Flutter', 'podhelper.rb')), binding)
end
